spring:
  jpa:
    open-in-view: false
    hibernate.ddl-auto: create-drop
  main:
    banner-mode: 'off'
  datasource:
    url: 'jdbc:h2:mem:testDB'
    driverClassName: org.h2.Driver
    username: sa
    password: sa
logging:
  level:
    root: warn
server:
  error:
    include-stacktrace: on_param