spring:
  jpa:
    open-in-view: false
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa

logging:
  level:
    root: warn

server:
  error:
  include-stacktrace: on_param
